name: ci
concurrency:
  group: ci/${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1m
      - uses: actions/checkout@v3


