name: wkrunevent

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsutils@main
        with:
          tasks: 'context'
          create-artifact: true
      - run: echo "${{ toJSON(github.event) }}"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
